# Site settings
title: HighwayHead
#email: koenboncquet@gmail.com
description: ""
baseurl: ""
# url: "http://yourdomain.com"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
